### ISSUE TITLE
how to get current user 

### ISSUE THREAD

**Issue by nyghtrocker** [ganagus/JwtRefreshSample#1]
I'm trying to adopt your code samples and having problem in getting current logging user id in controller.do you know how to get current user id inside controller in .net core 2.0

**Comment by ganagus** [comment]
You should include the username (or id) as part of the JWT claims in TokenController (AuthorizationServer). Sample:

            var claims = new Claim[]
            {
                new Claim(JwtRegisteredClaimNames.Sub, clientId),
                new Claim(JwtRegisteredClaimNames.Jti, Guid.NewGuid().ToString()),
                new Claim(JwtRegisteredClaimNames.Iat, now.ToUniversalTime().ToString(), ClaimValueTypes.Integer64),
                new Claim("Name", "the-username or full name")
            };

Then in your resource server's controllers, you can use User.Claims to get the username from claims.

**Comment by nyghtrocker** [comment]
Hi, Thanks you so much for the reply. I replaced clientId with  userId in claims and then I'm getting user info with _userManager.GetUserAsync(HttpContext.User);. This is working but i'm not sure if its ok to replace clientId with the userId . what do you think?

**Comment by nyghtrocker** [comment]
This line new Claim(JwtRegisteredClaimNames.Sub, userId)

**Comment by ganagus** [comment]
Refers to https://www.iana.org/assignments/jwt/jwt.xhtml, the Sub claim name identifies the Subject of the claim, it is more suitable for the client id, client name, or application name. We should use Name claim to idenfity user's Fullname, or username. 

I've updated the source code by adding Name claim to Jwt token. I also created an action in ResourceServer's controller to get the username. Please note that there are changes also in data model. You can examine the changes further in the source code. Feel free to discuss more about this change.

**Comment by nyghtrocker** [comment]
Thanks. It's working :)
